version: '3'
services:
  api:
    image: sbis-express-app
    build: .
    networks:
      - backend
    ports:
      - "3003:3003"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: sbis-express-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
